### ISSUE TITLE
Nomenclaturas candles

### ISSUE THREAD

**Issue by fioravantebossi** [fioravantebossi/ML#12]

**Comment by fbtrader** [comment]
Bears - participantes do mercado que tem a expectativa que o mesmo apresentará baixa, tentam tirar o lucro com isso

**Comment by fbtrader** [comment]
Bearish - a expectativa que o mercado será baixista.

**Comment by fbtrader** [comment]
![image](https://user-images.githubusercontent.com/39245364/40125717-f5c7e32e-5901-11e8-919e-35cdc786a459.png)

**Comment by fbtrader** [comment]
Bulls - participantes do mercado que tem a expectativa que o mesmo suba.

**Comment by fbtrader** [comment]
Bullish - a expectativa que o mercado suba
