### ISSUE TITLE
MACD

### ISSUE THREAD

**Issue by fioravantebossi** [fioravantebossi/ML#13]

**Comment by fbtrader** [comment]
MACD André Moraes + Andre Machado
Teoria de Dow - Preço desconta tudo, preço e volume e tomar decisão, tudo precisamos saber esta no preço. Preço é o mais importante, analise do preço.
OBV - Bom para antecipar reversões. (Volumétrico)
Indicadores em consolidações dão falsos sinais
Bom para tirar dúvida, confirmar o que estou vendo no preço, ou para contestar o que o preço esta dizendo.
Indicadores são atrasados.
