### ISSUE TITLE
Cap 1

### ISSUE THREAD

**Issue by fioravantebossi** [fioravantebossi/ML#5]
Book: Expert Advisor Programming For Metatrader 5 
Andrew R. Young

Chapter 1 - MQL5 Basics 3
MQL5 Programs 3
File Extensions 3
Other File Types 3
File Locations 4
MetaEditor 5
MQL5 Wizard 7
Compilation 8
Syntax 8
Identifiers 9
Comments 9

**Comment by fbtrader** [comment]
expert advisor is an automated trading program that can open, modify and close orders. (just one per chart)

**Comment by fbtrader** [comment]
An indicator displays technical analysis data on a chart or in a separate window using lines, histograms,
arrows, bars/candles or chart objects (multiple)

**Comment by fbtrader** [comment]
A script is a specialized program that performs a specific task. (one script per chart) (execute only once)

**Comment by fbtrader** [comment]
Extensions:
Source code: MQ5 file (.mq5)
EX5 file (.ex5): compiled
MQH file (.mqh): include

**Comment by fbtrader** [comment]
MetaEditor has a built-in MQL5 Reference, which is useful for looking up MQL5 functions and language
elements. Simply position the cursor over an MQL5 keyword and press F1 on your keyboard

**Comment by fbtrader** [comment]
https://www.youtube.com/watch?v=XVW_6X_uf8Q&index=2&list=PLltlMLQ7OLeKwyQwC8FhiKwjl9syKhOCK

**Comment by fbtrader** [comment]
Expert Advisor (generate) – This allows the user to create an expert advisor without any coding. The
generated expert advisor uses the MQL5 standard library.

**Comment by fbtrader** [comment]
New Class – This will create an include file with a class definition from a built-in template. The created
file is saved in the \MQL5\Experts folder, or a specified subfolder.

**Comment by fbtrader** [comment]
MQL5 is similar to other modern programming languages such as C++, C# or Java

**Comment by fbtrader** [comment]
When naming variables, functions and classes, you need to use a unique and descriptive identifier

You can use letters, numbers and the underscore character (_), although the first character in an identifier
should not be a number. The maximum length for an identifier is 64 characters. This give you a lot of room to
be creative, so use identifiers that are clear and descriptive.

Identifiers are case sensitive

**Comment by fbtrader** [comment]
Global variables, objects, classes and function names will capitalize the first letter of each word. For
example: MyFunction() or MyVariable


Local variables and objects, which are declared inside a function, will use camel case. This is where the
first letter is lower case, and the first letters of all other words are upper case. For example:
myVariable or localObject.

Constants are in all upper case. Use underscores to separate words, for example: MY_CONSTANT.

**Comment by fbtrader** [comment]
// This is a comment

/* This is a multi-line comment
These lines will be ignored by the compiler
x = y + z; */

**Comment by fbtrader** [comment]
In the Edit menu, under the Comments submenu, the Comment Lines menu item will
comment out the selected lines, while Uncomment Lines will remove comments from selected lines. The
Function Header menu item will insert a commented function header similar to those in the auto-generated
MQ5 files:
// Function header generated by Edit menu –> Comments –> Function Header
//+------------------------------------------------------------------+
//| |
//+------------------------------------------------------------------+
