### ISSUE TITLE
Estudo de domingo

### ISSUE THREAD

**Issue by fioravantebossi** [fioravantebossi/ML#7]

**Comment by fbtrader** [comment]
PETR4 em tendencia de alta, subir o stop nos fundos do gráfico de 60

**Comment by fbtrader** [comment]
Ver indicador difusor

**Comment by fbtrader** [comment]
![image](https://user-images.githubusercontent.com/39245364/39976197-c3ee570c-5708-11e8-92eb-710e2ec4757f.png)


Difusor quase rompendo para cima

**Comment by fbtrader** [comment]
Estudar teoria de dow
